[workspace]
members = [
  "fadroma",               # smart contract microframework
  "exchange",              # uniswap exchange contract implementation
  "factory",               # factory contract for creating exchanges
  "shared",                # shared types between all amm contracts
  "snip20-reference-impl", # snip20 token implementation with a modification to call back a contract after init
  "ido",                   # initial dex offering implementation
  "utils"                  # utility code used by contracts
]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
