[workspace]
members = [
  "exchange",              # uniswap exchange contract implementation
  "factory",               # factory contract for creating exchanges
  "snip20-reference-impl", # snip20 token implementation with a modification to call back a contract after init
  "lp-token",              # snip20 liquidity provider token
  "sienna-burner",         # burns SIENNA on each swap
  "api",                   # schema generator for all the above
  "fadroma/scrt-migrate"   # pause contracts and mark them for upgrade
]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
