[workspace]
members = [
  "kukumba",  # bdd testing framework
  "fadroma",  # smart contract microframework
  "token",    # any token that implements SNIP20
  "schedule", # model of the client's vesting logic
  "mgmt"      # smart contract that mints and vests tokens according to schedule
]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
