[workspace]
members = [
  "contracts/exchange",              # uniswap exchange contract implementation
  "contracts/factory",               # factory contract for creating exchanges
  "contracts/snip20-reference-impl", # snip20 token implementation with a modification to call back a contract after init
  "contracts/lp-token",              # snip20 liquidity provider token
  "contracts/sienna-burner",         # burns SIENNA on each swap
  "api",                             # schema generator for all of the above

  "libraries/amm-shared",          # definitions that are shared between AMM and IDO
  "libraries/fadroma/scrt-migrate" # pause contracts and mark them for upgrade
]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
