version: '3.4'

volumes: # clear those with `docker-compose down -v` to run "from scratch"
  secretd:
  secretcli:
  sgx-secrets:
  shared-keys:
services:
  localnet:
    image: enigmampc/secret-network-sw-dev
    network_mode: host
    entrypoint: /init.sh
    volumes:
      - './integration/localnet/init.sh:/init.sh:ro'
      - './integration/localnet/keys:/shared-keys:rw'
      - 'secretd:/root/.secretd:rw'
      - 'secretcli:/root/.secretcli:rw'
      - 'sgx-secrets:/root/.sgx-secrets:rw'
