version: '3.4'
volumes: # clear those with `docker-compose down -v` to run "from scratch"
  secretd:
  secretcli:
  sgx-secrets:
  shared-keys:
services:
  localnet:
    image: enigmampc/secret-network-sw-dev
    network_mode: host
    entrypoint: /init.sh
    volumes:
      - './localnet/init.sh:/init.sh:ro'
      - 'secretd:/root/.secretd:rw'
      - 'secretcli:/root/.secretcli:rw'
      - 'sgx-secrets:/root/.sgx-secrets:rw'
      - 'shared-keys:/shared-keys:rw'
  compare:
    build: ./scripts
    network_mode: host
    user: "1000:1000"
    volumes:
      - '.:/sienna:rw'
      - 'secretcli:/home/node/.secretcli:rw'
      - 'shared-keys:/shared-keys:rw'
      - '/var/run/docker.sock:/var/run/docker.sock:rw'
    entrypoint: /bin/bash
    working_dir: /sienna/scripts
    command: /sienna/scripts/compare.sh
