version: '3'
networks:
  sienna:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
services:
  localnet:
    image: enigmampc/secret-network-sw-dev
    volumes: [ '.:/sienna:ro' ]
    networks: [ sienna ]
    ports: [ "26657:26657", "26656:26656", "1317:1317" ]
