/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ReceiverCallbackMsg =
  | {
      activate: {
        /**
         * Time when the sale will end
         */
        end_time: number;
        /**
         * Time when the sale will start (if None, it will start immediately)
         */
        start_time?: number | null;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      pre_lock: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      swap: {
        /**
         * If the recipient of the funds is going to be someone different then the sender
         */
        recipient?: HumanAddr | null;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
export type HumanAddr = string;
