/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Handle =
  | {
      auth: AuthHandle;
      [k: string]: unknown;
    }
  | {
      create_viewing_key: {
        entropy: string;
        padding?: string | null;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      set_viewing_key: {
        key: string;
        padding?: string | null;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      immigration: ImmigrationHandle;
      [k: string]: unknown;
    }
  | {
      emigration: EmigrationHandle;
      [k: string]: unknown;
    }
  | {
      rewards: RewardsHandle;
      [k: string]: unknown;
    }
  | {
      drain: {
        key: string;
        recipient?: HumanAddr | null;
        snip20: ContractLinkFor_HumanAddr;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
export type AuthHandle =
  | {
      change_admin: {
        address: HumanAddr;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      create_viewing_key: {
        entropy: string;
        padding?: string | null;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      set_viewing_key: {
        key: string;
        padding?: string | null;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
export type HumanAddr = string;
export type ImmigrationHandle =
  | {
      enable_migration_from: ContractLinkFor_HumanAddr;
      [k: string]: unknown;
    }
  | {
      disable_migration_from: ContractLinkFor_HumanAddr;
      [k: string]: unknown;
    }
  | {
      request_migration: ContractLinkFor_HumanAddr;
      [k: string]: unknown;
    }
  | {
      receive_migration: Binary;
      [k: string]: unknown;
    };
/**
 * Binary is a wrapper around Vec<u8> to add base64 de/serialization with serde. It also adds some helper methods to help encode inline.
 *
 * This is only needed as serde-json-{core,wasm} has a horrible encoding for Vec<u8>
 */
export type Binary = string;
export type EmigrationHandle =
  | {
      enable_migration_to: ContractLinkFor_HumanAddr;
      [k: string]: unknown;
    }
  | {
      disable_migration_to: ContractLinkFor_HumanAddr;
      [k: string]: unknown;
    }
  | {
      export_state: HumanAddr;
      [k: string]: unknown;
    };
export type RewardsHandle =
  | {
      deposit: {
        amount: Uint128;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      withdraw: {
        amount: Uint128;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      claim: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      begin_epoch: {
        next_epoch: number;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      configure: RewardsConfig;
      [k: string]: unknown;
    }
  | {
      close: {
        message: string;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
export type Uint128 = string;

/**
 * Info needed to talk to a contract instance.
 */
export interface ContractLinkFor_HumanAddr {
  address: HumanAddr;
  code_hash: string;
  [k: string]: unknown;
}
/**
 * Reward pool configuration
 */
export interface RewardsConfig {
  bonding?: number | null;
  lp_token?: ContractLinkFor_HumanAddr | null;
  reward_token?: ContractLinkFor_HumanAddr | null;
  reward_vk?: string | null;
  timekeeper?: HumanAddr | null;
  [k: string]: unknown;
}
