export function abs (...args: any): any;
export function args (...args: any): any;
export function cargo (...args: any): any;
export function combine (...args: any): any;
export function fmtSienna (...args: any): any;
export const projectRoot: string;
export function genCoverage (...args: any): any;
export function genSchema (...args: any): any;
export function genDocs (...args: any): any;
export function runTests (...args: any): any;
export function runDemo (...args: any): any;
