[package]
name = "amm-snip20"
version = "0.1.0"
authors = ["Asparuh Kamenov <asparuh@hack.bg>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
amm-shared = { path = "../../libraries/amm-shared" }
