/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HumanAddr = string;
/**
 * Binary is a wrapper around Vec<u8> to add base64 de/serialization with serde. It also adds some helper methods to help encode inline.
 *
 * This is only needed as serde-json-{core,wasm} has a horrible encoding for Vec<u8>
 */
export type Binary = string;

export interface InitMsg {
  admin?: HumanAddr | null;
  exchange_settings: ExchangeSettings;
  ido_contract: ContractInstantiationInfo;
  launchpad_contract: ContractInstantiationInfo;
  lp_token_contract: ContractInstantiationInfo;
  pair_contract: ContractInstantiationInfo;
  prng_seed: Binary;
  snip20_contract: ContractInstantiationInfo;
  [k: string]: unknown;
}
export interface ExchangeSettings {
  sienna_burner?: HumanAddr | null;
  sienna_fee: Fee;
  swap_fee: Fee;
  [k: string]: unknown;
}
export interface Fee {
  denom: number;
  nom: number;
  [k: string]: unknown;
}
/**
 * Info needed to instantiate a contract.
 */
export interface ContractInstantiationInfo {
  code_hash: string;
  id: number;
}
