[package]
name = "sienna-rpt"
version = "2.0.0"
authors = ["Adam Avramov <adam@hack.bg>", "Wiz1991 <elvis.private20@gmail.com"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"
doctest = false

[dependencies]
fadroma = { path = "../../../deps/fadroma/crates/fadroma", features = [
  "derive",
] }
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
linear-map = { path = "../../../libraries/linear-map" }
sienna-mgmt = { path = "../mgmt" }


[dev-dependencies]
kukumba = { git = "https://github.com/hackbg/kukumba", branch = "21.04" }
snip20-sienna = { path = "../snip20-sienna" }

[features]
default = []
