[package]
name = "sienna-rewards"
version = "2.0.0"
authors = ["Adam Avramov <adam@hack.bg>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false
path = "rewards.rs"

[dependencies]
fadroma = { path = "../../libraries/fadroma-21.07/core", features = [
  "scrt-addr",
  "scrt-admin",
  "scrt-callback",
  "scrt-contract",
  "scrt-migrate",
  "scrt-snip20-api",
  "scrt-storage",
  "scrt-utils",
  "scrt-vk"
] }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
wasm-bindgen = { optional = true, version = "0.2" }

[dev-dependencies]
fadroma = { path = "../../libraries/fadroma-21.07/core", features = [ "scrt-harness" ] }
kukumba = { path = "../../libraries/kukumba" }
serde_json = "1.0"

[features]
default = []
browser = ["fadroma/browser", "wasm-bindgen"]
