/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | {
      config: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      borrow_rate: {
        market_size: Decimal256;
        num_borrows: Decimal256;
        reserves: Decimal256;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      supply_rate: {
        market_size: Decimal256;
        num_borrows: Decimal256;
        reserve_factor: Decimal256;
        reserves: Decimal256;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      admin: QueryMsg1;
      [k: string]: unknown;
    };
/**
 * A fixed-point decimal value with 18 fractional digits, i.e. Decimal256(1_000_000_000_000_000_000) == 1.0 The greatest possible value that can be represented is 115792089237316195423570985008687907853269984665640564039457.584007913129639935 (which is (2^128 - 1) / 10^18)
 */
export type Decimal256 = string;
export type QueryMsg1 = {
  admin: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
};
