/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HandleMsg = {
  set_price: {
    price: Uint128;
    symbol: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
};
export type Uint128 = string;
