/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | {
      get_reference_data: {
        base_symbol: string;
        quote_symbol: string;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      get_reference_data_bulk: {
        base_symbols: string[];
        quote_symbols: string[];
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
