@startuml
skinparam backgroundColor #ccc
skinparam sequence.LifeLineBorderColor #555
actor Admin order 0
entity SIENNA order 5
entity MGMT order 2
entity RPT order 4
== Normal operation ==
note over MGMT, SIENNA #ffffff: see MGMT/RPT migration instructions for examples of normal operation
== Entering emergency mode ==
Admin -> SIENNA : **tx** SetStatus!(Paused(reason))
note right #ffaa00: status = Paused(reason)
create actor Claimant order 1
Admin -[hidden]-> Claimant
Claimant -> MGMT : **tx** Claim!
MGMT -x SIENNA : **tx** Transfer!
note right #ff8888: can't claim when token is paused
SIENNA -> MGMT : **err** "token paused (reason: [reason])"
MGMT -x Claimant : **err** "token paused (reason: [reason])"
Claimant -> SIENNA : **q** Balance?
SIENNA -> Claimant : **res** (same balance as before)
Claimant -> RPT : **tx** Vest!
RPT -x SIENNA : **tx** Transfer!
note right #ff8888: can't claim when token is paused
SIENNA -> RPT : **err** "token paused (reason: [reason])"
RPT -x Claimant : **err** "token paused (reason: [reason])"
== Updating SIENNA in MGMT ==
create entity newSIENNA order 5
Admin -> newSIENNA : **init** Deploy
Admin -> SIENNA : **tx** SetStatus!(MigrateTo(newSIENNA))
note right #ffaa00: status = MigrateTo(newSIENNA)
Admin -x SIENNA : **tx** SetStatus!(Normal)
note right #ff8888: **irreversible!**
Admin -> MGMT : **tx** SetToken!(newSIENNA)
note right #00ff00: state.token = newSIENNA\nstate.prev_token = SIENNA
Claimant -> MGMT : **tx** Claim!
MGMT -> newSIENNA : **tx** Transfer!
note right #00ff00: transfer newly unlocked balance
MGMT -> newSIENNA : **tx** MigrateAccount!(state.prev_token, Claimant)
note right #00ff00: copy balance and allowance from parent
newSIENNA -> SIENNA : **q** Balance(Claimant)
SIENNA -> newSIENNA : **res** Balance(Claimant)
note right #00ff00: balance unlocked from previous token is also there
MGMT -> Claimant : **log:** "The SIENNA token is moving to [newSIENNA] (reason: [reason]).\nYour balance has been automatically migrated.\nPlease use that address in place of [SIENNA] from now on."
note right: this should not happen more than once;\nshould this be recursive, and should it mint/burn?
== Updating SIENNA in RPT ==
Admin -> RPT : **tx** SetToken!(newSIENNA)
note right #00ff00: state.token = newSIENNA\nstate.prev_token = SIENNA
Claimant -> RPT : **tx** Claim!
RPT -> newSIENNA : **tx** Transfer!
RPT -> SIENNA : **tx** Migrate!(Claimant)
RPT -> Claimant : **log:** "The SIENNA token is moving to [newSIENNA] (reason: [reason]).\nBalances have been automatically migrated.\nPlease use that address in place of [SIENNA] from now on."
@enduml
