/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | {
      token_info: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      balance: {
        address: HumanAddr;
        key: string;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      balance_underlying: {
        block?: number | null;
        method: AuthMethodFor_MarketPermissions;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      state: {
        block?: number | null;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      underlying_asset: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      borrow_rate: {
        block?: number | null;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      supply_rate: {
        block?: number | null;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      exchange_rate: {
        block?: number | null;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      account: {
        block?: number | null;
        method: AuthMethodFor_MarketPermissions;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      id: {
        method: AuthMethodFor_MarketPermissions;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      borrowers: {
        block: number;
        pagination: Pagination;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      admin: QueryMsg1;
      [k: string]: unknown;
    }
  | {
      killswitch: QueryMsg1;
      [k: string]: unknown;
    };
export type HumanAddr = string;
export type AuthMethodFor_MarketPermissions =
  | {
      permit: PermitFor_MarketPermissions;
      [k: string]: unknown;
    }
  | {
      viewing_key: {
        address: HumanAddr;
        key: string;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      internal: {
        address: HumanAddr;
        key: MasterKey;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
export type MarketPermissions = "account_info" | "balance" | "id";
/**
 * A single viewing key that is shared throughout the protocol so that private data can be viewied internally.
 */
export type MasterKey = ViewingKey;
export type ViewingKey = string;
export type QueryMsg1 = {
  admin: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
};

export interface PermitFor_MarketPermissions {
  address: HumanAddr;
  params: PermitParamsFor_MarketPermissions;
}
export interface PermitParamsFor_MarketPermissions {
  allowed_tokens: HumanAddr[];
  chain_id: string;
  permissions: MarketPermissions[];
  permit_name: string;
}
export interface Pagination {
  limit: number;
  start: number;
}
