/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ReceiverCallbackMsg =
  | "deposit"
  | {
      repay: {
        /**
         * Repay someone else's debt.
         */
        borrower?: Binary | null;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      liquidate: {
        borrower: Binary;
        collateral: HumanAddr;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
/**
 * Binary is a wrapper around Vec<u8> to add base64 de/serialization with serde. It also adds some helper methods to help encode inline.
 *
 * This is only needed as serde-json-{core,wasm} has a horrible encoding for Vec<u8>
 */
export type Binary = string;
export type HumanAddr = string;
