version: '3.4'
services:

  localnet:
    image: enigmampc/secret-network-sw-dev
    network_mode: host
    volumes:
      - './.secretd:/root/.secretd:rw'
      - './.secretcli:/root/.secretcli:rw'
      - './.sgx-secrets:/root/.sgx-secrets:rw'

  compare:
    build: .
    network_mode: host
    volumes:
      - '..:/sienna:ro'
      - './.secretcli:/root/.secretcli:rw'
    command: /sienna/scripts/compare.js
