/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | {
      markets: {
        pagination: Pagination;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      market: {
        address: HumanAddr;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      entered_markets: {
        method: AuthMethodFor_OverseerPermissions;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      account_liquidity: {
        block?: number | null;
        borrow_amount: Uint256;
        market?: HumanAddr | null;
        method: AuthMethodFor_OverseerPermissions;
        redeem_amount: Uint256;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      can_transfer_internal: {
        address: HumanAddr;
        amount: Uint256;
        block: number;
        key: MasterKey;
        market: HumanAddr;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      seize_amount: {
        borrowed: HumanAddr;
        collateral: HumanAddr;
        repay_amount: Uint256;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      config: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      admin: QueryMsg1;
      [k: string]: unknown;
    }
  | {
      auth: QueryMsg1;
      [k: string]: unknown;
    };
export type HumanAddr = string;
export type AuthMethodFor_OverseerPermissions =
  | {
      permit: PermitFor_OverseerPermissions;
      [k: string]: unknown;
    }
  | {
      viewing_key: {
        address: HumanAddr;
        key: string;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      internal: {
        address: HumanAddr;
        key: MasterKey;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
export type OverseerPermissions = "account_info";
/**
 * A single viewing key that is shared throughout the protocol so that private data can be viewied internally.
 */
export type MasterKey = ViewingKey;
export type ViewingKey = string;
export type Uint256 = string;
export type QueryMsg1 = {
  admin: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
};

export interface Pagination {
  limit: number;
  start: number;
}
export interface PermitFor_OverseerPermissions {
  address: HumanAddr;
  params: PermitParamsFor_OverseerPermissions;
}
export interface PermitParamsFor_OverseerPermissions {
  allowed_tokens: HumanAddr[];
  chain_id: string;
  permissions: OverseerPermissions[];
  permit_name: string;
}
