@startuml

skinparam backgroundColor #ccc
skinparam sequence.LifeLineBorderColor #555

actor Admin
entity SIENNA
entity MGMT
entity RPT

== Deployment ==

Admin -> SIENNA : **init** Init
Admin -> MGMT : **init** Init(token=SIENNA, schedule=Schedule(rpt=DUMMY))
note right #00ff00: status = Prelaunch
Admin -> RPT : **init** Init(token=SIENNA, mgmt=MGMT)
Admin -> MGMT : **tx** UpdateSchedule!(Schedule(rpt=RPT))
Admin -> MGMT : **tx** Acquire!(token=MGMT)
Admin -> MGMT : **tx** Launch!
note right #00ff00: status = Launched(date)
MGMT -> SIENNA : **tx** Mint!

@enduml
