@startuml

actor Admin
actor User
participant Old
participant New
participant LPToken

== Initiate migration ==
Admin -> New: Deploy new version
Admin -> Old: EmigrationHandle::EnableMigrationTo(New)
Admin -> New: ImmigrationHandle::EnableMigrationFrom(Old)
Admin -> Old: ClosePool

== Migrate ==
User -> New: ImmigrationHandle::RequestMigration
New -> Old: EmigrationHandle::ExportState
Old -> LPToken: Transfer(stake)
LPToken -> New: (transfers)
Old -> New: ImmigrationHandle::ReceiveMigration

@enduml
