[package]
name = "sienna-mgmt"
version = "3.0.0"
authors = ["Adam Avramov <adam@hack.bg>", "Wiz1991 <elvis.private20@gmail.com"]
edition = "2018"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"
doctest = false

[dependencies]
fadroma = { path = "../../../deps/fadroma/crates/fadroma", features = [
  "derive",
] }
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

linear-map = { path = "../../../libraries/linear-map" }
sienna-schedule = { path = "../../../libraries/schedule" }

[features]
default = []
# this allows the contract to be build for a mock environment
# that is hosted in a browser. allows dashboard and fast integration tests
