/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HandleMsg =
  | {
      update_assets: {
        assets: Asset[];
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      admin: HandleMsg1;
      [k: string]: unknown;
    };
export type HumanAddr = string;
export type HandleMsg1 =
  | {
      change_admin: {
        address: HumanAddr;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      accept_admin: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };

export interface Asset {
  address: HumanAddr;
  symbol: string;
}
