/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | {
      price: {
        base: AssetType;
        quote: AssetType;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      prices: {
        base: AssetType[];
        quote: AssetType[];
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      admin: QueryMsg1;
      [k: string]: unknown;
    };
export type AssetType =
  | {
      symbol: string;
      [k: string]: unknown;
    }
  | {
      address: HumanAddr;
      [k: string]: unknown;
    };
export type HumanAddr = string;
export type QueryMsg1 = {
  admin: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
};
