/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Handle =
  | {
      change_admin: {
        address: HumanAddr;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      set_provided_token: {
        address: HumanAddr;
        code_hash: string;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      change_ratio: {
        denominator: Uint128;
        numerator: Uint128;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      change_threshold: {
        threshold: number;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      change_cooldown: {
        cooldown: number;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      close_pool: {
        message: string;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      create_viewing_key: {
        entropy: string;
        padding?: string | null;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      set_viewing_key: {
        key: string;
        padding?: string | null;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      lock: {
        amount: Uint128;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      retrieve: {
        amount: Uint128;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      claim: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
export type HumanAddr = string;
export type Uint128 = string;
