/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Query =
  | {
      admin: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      pool_info: {
        at: number;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      user_info: {
        address: HumanAddr;
        at: number;
        key: string;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      token_info: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      balance: {
        address: HumanAddr;
        key: string;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
export type HumanAddr = string;
