/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Response =
  | {
      pool_info: {
        it_is_now: number;
        lp_token: ContractInstanceFor_HumanAddr;
        pool_balance: Uint128;
        pool_claimed: Uint128;
        pool_cooldown: number;
        pool_last_update: number;
        pool_lifetime: Uint256;
        pool_liquid: Uint128;
        pool_locked: Uint128;
        pool_threshold: number;
        reward_token: ContractInstanceFor_HumanAddr;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      user_info: {
        it_is_now: number;
        pool_last_update: number;
        pool_lifetime: Uint256;
        pool_locked: Uint128;
        user_age: number;
        user_claimable: Uint128;
        user_claimed: Uint128;
        user_cooldown: number;
        user_earned: Uint128;
        user_last_update?: number | null;
        user_lifetime: Uint256;
        user_locked: Uint128;
        user_share: Uint128;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      admin: {
        address: HumanAddr;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      token_info: {
        decimals: number;
        name: string;
        symbol: string;
        total_supply?: Uint128 | null;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      balance: {
        amount: Uint128;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
export type HumanAddr = string;
export type Uint128 = string;
export type Uint256 = string;

/**
 * Info needed to talk to a contract instance.
 */
export interface ContractInstanceFor_HumanAddr {
  address: HumanAddr;
  code_hash: string;
  [k: string]: unknown;
}
