[package]
name    = "sienna-tge-schema"
version = "0.0.0"
authors = ["Adam A. <adam@hack.bg>"]
edition = "2018"

[dependencies]
cosmwasm-schema = { git = "https://github.com/enigmampc/SecretNetwork", tag = "v1.0.0" }
snip20-reference-impl = { path = "../contracts/token" }
sienna-mgmt  = { path = "../contracts/mgmt" }
sienna-rpt   = { path = "../contracts/rpt" }
sienna-rewards = { path = "../contracts/rewards" }

[[bin]]
name = "schema"
path = "schema.rs"
