[package]
name    = "sienna-rewards-schema"
version = "0.0.0"
authors = ["Adam A. <adam@hack.bg>"]
edition = "2018"

[dependencies]
cosmwasm-schema = { git = "https://github.com/enigmampc/SecretNetwork", tag = "v1.0.0" }
gov-token       = { path = "../rewards/contracts/gov-token" }
lp-staking      = { path = "../rewards/contracts/lp-staking" }
weight-master   = { path = "../rewards/contracts/weight-master" }

[[bin]]
name = "schema"
path = "schema.rs"
