[package]
name    = "sienna-amm-schema"
version = "0.0.0"
authors = ["Adam A. <adam@hack.bg>"]
edition = "2018"

[dependencies]
cosmwasm-schema       = { git = "https://github.com/enigmampc/SecretNetwork", tag = "v1.0.0" }
exchange              = { path = "../contracts/exchange" }
factory               = { path = "../contracts/factory" }
lp-token              = { path = "../contracts/lp-token" }
sienna-burner         = { path = "../contracts/sienna-burner" }
snip20-reference-impl = { path = "../contracts/snip20-reference-impl" }
sienna-amm-shared     = { path = "../libraries/amm-shared" }

[[bin]]
name = "schema"
path = "schema.rs"
