name: AMM
on: [push, pull_request]
jobs:
  cargo:
    name: Unit tests and documentation
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchain that allows macro backtrace
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Change directory
        run: cd amm
      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked
        env:
          RUST_BACKTRACE: 1
          RUSTFLAGS: -Zmacro-backtrace
      - name: Render Cargo documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
        env:
          RUST_BACKTRACE: 1

