on: [push, pull_request]
name: SIENNA CI
jobs:
  test:
    name: Unit tests and documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install toolchain that allows macro backtrace
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true
      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked
        env:
          RUST_BACKTRACE: 1
          RUSTFLAGS: -Zmacro-backtrace
      - name: Render documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
        env:
          RUST_BACKTRACE: 1

  coverage:
    name: Test coverage report (Tarpaulin)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install toolchain that works with Tarpaulin
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
      - name: Install Tarpaulin
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-tarpaulin
        env:
          RUST_BACKTRACE: 1
      - name: Generate test coverage
        uses: actions-rs/cargo@v1
        with:
          command: tarpaulin
          args: --out=Html --output-dir=docs --exclude-files=libraries/platform
        env:
          RUST_BACKTRACE: 1
      - name: Commit coverage report
        run: |
          git checkout $(git symbolic-ref --short HEAD)
          git add docs/tarpaulin-report.html
          git diff --cached
          git config --global user.email "hack@hack.bg"
          git config --global user.name "hack.bg"
          git commit -m "🤖 updated coverage @ $(date -u)" || true
          git push
