on: [push, pull_request]
name: Project-wide tasks
jobs:

  docs:
    name: Rust documentation
    runs-on: ubuntu-latest
    steps:
      - name: Install Node and Yarn
        uses: actions/setup-node@v2
        with: { node-version: "14.x" }
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with: { profile: minimal, toolchain: 1.49.0, target: wasm32-unknown-unknown, override: true }
      - name: Checkout sources
        uses: actions/checkout@v2
        with: { submodules: true }
      - name: Install JS dependencies
        run: yarn
      - name: Generate documentation
        run: ./sienna docs

  test:
    name: Unit test suites of all contracts
    runs-on: ubuntu-latest
    steps:
      - name: Install Node and Yarn
        uses: actions/setup-node@v2
        with: { node-version: "14.x" }
      - name: Install toolchain that allows macro backtrace
        uses: actions-rs/toolchain@v1
        with: { profile: minimal, toolchain: nightly, target: wasm32-unknown-unknown, override: true }
      - name: Checkout sources
        uses: actions/checkout@v2
        with: { submodules: true }
      - name: Install JS dependencies
        run: yarn
      - name: Run tests
        run: ./sienna test

  coverage:
    name: Unit test coverage report
    runs-on: ubuntu-latest
    steps:
      - name: Install Node and Yarn
        uses: actions/setup-node@v2
        with: { node-version: "14.x" }
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with: { profile: minimal, toolchain: 1.49.0, target: wasm32-unknown-unknown, override: true }
      - name: Checkout sources
        uses: actions/checkout@v2
        with: { submodules: true }
      - name: Install JS dependencies
        run: yarn
      - name: Generate coverage report
        run: ./sienna coverage

  schema:
    name: API schema of all contracts
    runs-on: ubuntu-latest
    steps:
      - name: Install Node and Yarn
        uses: actions/setup-node@v2
        with: { node-version: "14.x" }
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with: { profile: minimal, toolchain: 1.49.0, target: wasm32-unknown-unknown, override: true }
      - name: Checkout sources
        uses: actions/checkout@v2
        with: { submodules: true }
      - name: Install JS dependencies
        run: yarn
      - name: Generate schema
        run: ./sienna schema
