# Based on https://github.com/actions-rs/example/blob/master/.github/workflows/quickstart.yml
on: [push, pull_request]
name: Rewards
jobs:

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.49.0
          target: wasm32-unknown-unknown
          override: true

      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Change directory
        run: cd rewards

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked
        env:
          RUST_BACKTRACE: 1
