# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: wSIENNA
on: [push, pull_request]
jobs:
  wsienna:
    name: Test wSIENNA
    defaults: { run: { working-directory: contracts/wrapped } }
    runs-on: ubuntu-latest
    steps:
    - { uses: actions/checkout@v2, with: { fetch-depth: 100 } }
    - name: Cache node modules
      uses: actions/cache@v2
      env: { cache-name: cache-node-modules-wsienna }
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Fetch code and build using Nodejs 14.x
      uses: actions/setup-node@v2
      with: { node-version: 14.x }
    - run:
        npm ci
        npm run test
        npm run coverage
  wsienna-fixes:
    name: Test wSIENNA w/fixes
    defaults: { run: { working-directory: contracts/wrapped-fixes } }
    runs-on: ubuntu-latest
    steps:
    - { uses: actions/checkout@v2, with: { fetch-depth: 100 } }
    - name: Cache node modules
      uses: actions/cache@v2
      env: { cache-name: cache-node-modules-wsienna }
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Fetch code and build using Nodejs 14.x
      uses: actions/setup-node@v2
      with: { node-version: 14.x }
    - run:
        npm ci
        npm run test
        npm run coverage
